version: '3.8'

services:
  backend:
    build: .
    container_name: AIAM-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: admin
      DB_NAME_DEVELOPMENT: AIAM
      DB_DIALECT: postgres
      NODE_ENV: development
      RABBITMQ_URL: amqp://rabbitmq:5672
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: aiam-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: AIAM
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: aiam-rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672"  
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  postgres-data:
  rabbitmq-data:
